---
- name: Load test config
  include_vars: test.yml
  when: test|bool

- name: Log Archive | Create directories
  file:
    path: "{{ logarchive_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Log Archive | Copy script
  copy:
    src: logarchive.py
    dest: "{{ logarchive_dir }}/logarchive.py"
    owner: root
    group: root
    mode: 0700

- name: Cold Storage | Copy script
  copy:
    src: coldstorage.py
    dest: "{{ logarchive_dir }}/coldstorage.py"
    owner: root
    group: root
    mode: 0700

- name: Log Archive | Copy configs (cfg files)
  template:
    src: default.cfg
    dest: "{{ logarchive_dir }}/default.cfg"
    owner: root
    group: root
    mode: 0600
    force: yes

- name: Log Archive | Setup cron
  template:
    src: logarchive.cron
    dest: "/etc/cron.d/logarchive{{ cluster }}"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Cold Storage | Setup cron
  template:
    src: coldstorage.cron
    dest: "/etc/cron.d/coldstorage{{ cluster }}"
    owner: root
    group: root
    mode: 0644
    force: no
